// Home Page - Landing page with hero section
import React from 'react';
import { Link } from 'react-router-dom';
import { 
  MapPin, Shield, Compass, Sparkles, Users, 
  ChevronRight, Star, Globe, Zap
} from 'lucide-react';

const features = [
  {
    icon: Sparkles,
    title: 'AI-Powered Itineraries',
    description: 'Get personalized day-by-day travel plans generated by advanced AI',
  },
  {
    icon: Shield,
    title: 'Solo Safety System',
    description: 'Women safety mode with safe area recommendations and safety scores',
  },
  {
    icon: Compass,
    title: 'Fatigue-Aware Planning',
    description: 'Smart scheduling that considers your energy levels throughout the day',
  },
  {
    icon: Star,
    title: 'Hidden Gems Discovery',
    description: 'Find local favorites using our inverse popularity algorithm',
  },
  {
    icon: Zap,
    title: 'Dynamic Replanning',
    description: 'Skip a place? We automatically reorganize your remaining itinerary',
  },
  {
    icon: Users,
    title: 'Local Guide Network',
    description: 'Connect with verified local guides for authentic experiences',
  },
];

const destinations = [
  { name: 'Paris', image: '🗼', tag: 'Culture' },
  { name: 'Tokyo', image: '🏯', tag: 'Adventure' },
  { name: 'Bangkok', image: '🛕', tag: 'Food' },
  { name: 'Rome', image: '🏛️', tag: 'History' },
  { name: 'Barcelona', image: '⛪', tag: 'Art' },
  { name: 'New York', image: '🗽', tag: 'Urban' },
];

function Home() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-primary-600 via-primary-500 to-accent-500 text-white">
        <div className="absolute inset-0 bg-black/10" />
        <div className="relative max-w-7xl mx-auto px-4 py-20 md:py-32">
          <div className="max-w-3xl">
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              AI Travel Planner
              <span className="block text-primary-100">Solo Traveller Edition</span>
            </h1>
            <p className="text-xl md:text-2xl text-primary-100 mb-8">
              Generate personalized, safe, and optimized travel itineraries in seconds. 
              Perfect for solo adventurers who want to explore smart.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                to="/plan"
                className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-white text-primary-600 rounded-xl font-semibold text-lg hover:bg-primary-50 transition-colors"
              >
                <Globe size={24} />
                Start Planning
                <ChevronRight size={20} />
              </Link>
              <Link
                to="/hidden-gems"
                className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-primary-700/50 text-white rounded-xl font-semibold text-lg hover:bg-primary-700 transition-colors"
              >
                <Star size={24} />
                Explore Hidden Gems
              </Link>
            </div>
          </div>
        </div>
        
        {/* Wave decoration */}
        <div className="absolute bottom-0 left-0 right-0">
          <svg viewBox="0 0 1440 120" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 120L60 105C120 90 240 60 360 45C480 30 600 30 720 37.5C840 45 960 60 1080 67.5C1200 75 1320 75 1380 75L1440 75V120H1380C1320 120 1200 120 1080 120C960 120 840 120 720 120C600 120 480 120 360 120C240 120 120 120 60 120H0Z" fill="white"/>
          </svg>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Travel Smarter, Not Harder
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI understands your mood, budget, and safety needs to create the perfect itinerary
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div 
                  key={index}
                  className="p-6 rounded-2xl bg-gray-50 hover:bg-primary-50 transition-colors group"
                >
                  <div className="w-12 h-12 rounded-xl bg-primary-100 text-primary-600 flex items-center justify-center mb-4 group-hover:bg-primary-500 group-hover:text-white transition-colors">
                    <Icon size={24} />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>
      
      {/* Popular Destinations */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Popular Destinations
            </h2>
            <p className="text-xl text-gray-600">
              Start exploring these amazing cities
            </p>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {destinations.map((dest, index) => (
              <Link
                key={index}
                to={`/plan?destination=${dest.name}`}
                className="bg-white rounded-2xl p-6 text-center hover:shadow-lg transition-shadow group"
              >
                <div className="text-5xl mb-3">{dest.image}</div>
                <h3 className="font-semibold text-gray-900 group-hover:text-primary-600 transition-colors">
                  {dest.name}
                </h3>
                <span className="text-sm text-gray-500">{dest.tag}</span>
              </Link>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-primary-600 to-accent-600 text-white">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Ready to Plan Your Solo Adventure?
          </h2>
          <p className="text-xl text-primary-100 mb-8">
            Join thousands of solo travelers who plan smarter with AI
          </p>
          <Link
            to="/plan"
            className="inline-flex items-center justify-center gap-2 px-10 py-4 bg-white text-primary-600 rounded-xl font-semibold text-lg hover:bg-primary-50 transition-colors"
          >
            <MapPin size={24} />
            Create Your Itinerary
            <ChevronRight size={20} />
          </Link>
        </div>
      </section>
    </div>
  );
}

export default Home;
