// Home / Landing Page - Premium design with animated hero
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, useScroll, useTransform } from 'framer-motion';
import {
  MapPin, Shield, Compass, Sparkles, Users, ChevronRight,
  Star, Globe, Zap, Heart, Map, ArrowRight, Play, Quote
} from 'lucide-react';
import AnimatedPage, { StaggerContainer, staggerItem } from '../components/ui/AnimatedPage';

// ========== Animated Headline ==========
function TypewriterHeadline() {
  const words = ['Smart', 'Safe', 'Better'];
  const [wordIndex, setWordIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setWordIndex(prev => (prev + 1) % words.length);
    }, 2500);
    return () => clearInterval(interval);
  }, []);

  return (
    <span className="relative inline-block">
      {words.map((word, i) => (
        <motion.span
          key={word}
          className="absolute left-0 gradient-text"
          initial={{ opacity: 0, y: 20 }}
          animate={{
            opacity: i === wordIndex ? 1 : 0,
            y: i === wordIndex ? 0 : -20,
          }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
        >
          {word}
        </motion.span>
      ))}
      {/* Invisible text to maintain width */}
      <span className="invisible">Better.</span>
    </span>
  );
}

// ========== Features ==========
const features = [
  {
    icon: Sparkles,
    title: 'AI-Powered Itineraries',
    description: 'Get personalized day-by-day travel plans generated by advanced AI that adapts to your style',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    icon: Shield,
    title: 'Solo Safety System',
    description: 'Women safety mode, SOS alerts, and safe area recommendations with real-time scoring',
    gradient: 'from-rose-500 to-pink-500',
  },
  {
    icon: Compass,
    title: 'Fatigue-Aware Planning',
    description: 'Smart scheduling considers your energy levels and walking tolerance throughout the day',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    icon: Star,
    title: 'Hidden Gems Discovery',
    description: 'Find local favorites and off-the-beaten-path spots with our community-driven algorithm',
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    icon: Zap,
    title: 'Dynamic Replanning',
    description: 'Weather changed? Skip a place? We auto-reorganize your remaining itinerary instantly',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    icon: Users,
    title: 'Local Guide Network',
    description: 'Connect with verified local guides for authentic experiences and insider knowledge',
    gradient: 'from-indigo-500 to-blue-500',
  },
];

// ========== Testimonials ==========
const testimonials = [
  {
    name: 'Sarah K.',
    role: 'Solo Backpacker',
    text: 'TriPlanner transformed my solo trip to Southeast Asia. The safety features gave me and my parents peace of mind.',
    avatar: '👩‍🦰',
    rating: 5,
  },
  {
    name: 'Marcus J.',
    role: 'Digital Nomad',
    text: 'The AI itinerary was spot-on — it even found hidden cafés I would have never discovered. Game-changing app!',
    avatar: '👨‍💻',
    rating: 5,
  },
  {
    name: 'Priya M.',
    role: 'Weekend Explorer',
    text: 'Budget mode saved me 40% on my Barcelona trip. The backpacker suggestions were genuinely helpful and accurate.',
    avatar: '👩‍🎓',
    rating: 5,
  },
];

// ========== Destinations ==========
const destinations = [
  { name: 'Paris', emoji: '🗼', tag: 'Culture', color: 'from-pink-400 to-rose-500' },
  { name: 'Tokyo', emoji: '🏯', tag: 'Adventure', color: 'from-red-400 to-orange-500' },
  { name: 'Bangkok', emoji: '🛕', tag: 'Food', color: 'from-amber-400 to-yellow-500' },
  { name: 'Rome', emoji: '🏛️', tag: 'History', color: 'from-emerald-400 to-teal-500' },
  { name: 'Barcelona', emoji: '⛪', tag: 'Art', color: 'from-blue-400 to-indigo-500' },
  { name: 'New York', emoji: '🗽', tag: 'Urban', color: 'from-violet-400 to-purple-500' },
];

// ========== Stats ==========
const stats = [
  { number: '50K+', label: 'Trips Planned' },
  { number: '120+', label: 'Countries' },
  { number: '4.9', label: 'User Rating' },
  { number: '99%', label: 'Safety Score' },
];

function Home() {
  const { scrollYProgress } = useScroll();
  const heroOpacity = useTransform(scrollYProgress, [0, 0.15], [1, 0]);
  const heroScale = useTransform(scrollYProgress, [0, 0.15], [1, 0.95]);

  return (
    <AnimatedPage className="overflow-hidden">
      {/* ===== HERO SECTION ===== */}
      <motion.section
        style={{ opacity: heroOpacity, scale: heroScale }}
        className="relative min-h-[90vh] flex items-center justify-center overflow-hidden"
      >
        {/* Animated gradient background */}
        <div className="absolute inset-0 bg-gradient-to-br from-primary-600 via-primary-500 to-accent-600 dark:from-primary-900 dark:via-surface-900 dark:to-accent-900">
          {/* Floating blobs */}
          <motion.div
            className="absolute top-1/4 left-1/4 w-96 h-96 rounded-full bg-white/5 blur-3xl"
            animate={{ x: [0, 50, 0], y: [0, -30, 0] }}
            transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
          />
          <motion.div
            className="absolute bottom-1/4 right-1/4 w-80 h-80 rounded-full bg-accent-400/10 blur-3xl"
            animate={{ x: [0, -40, 0], y: [0, 40, 0] }}
            transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
          />
          <motion.div
            className="absolute top-1/2 left-1/2 w-64 h-64 rounded-full bg-primary-300/10 blur-3xl"
            animate={{ x: [0, 30, -30, 0], y: [0, -50, 20, 0] }}
            transition={{ duration: 12, repeat: Infinity, ease: 'easeInOut' }}
          />
        </div>

        {/* Grid pattern */}
        <div className="absolute inset-0 opacity-5"
          style={{
            backgroundImage: 'radial-gradient(circle at 1px 1px, white 1px, transparent 0)',
            backgroundSize: '40px 40px'
          }}
        />

        {/* Content */}
        <div className="relative max-w-5xl mx-auto px-4 text-center py-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <motion.div
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-md border border-white/20 mb-8"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 }}
            >
              <Sparkles size={16} className="text-yellow-300" />
              <span className="text-white/90 text-sm font-medium">AI-Powered Travel Planning</span>
            </motion.div>

            <h1 className="text-5xl sm:text-6xl md:text-7xl font-extrabold text-white mb-6 leading-tight">
              Plan Smart.{' '}
              <br className="hidden sm:block" />
              Travel{' '}
              <TypewriterHeadline />
            </h1>

            <p className="text-lg sm:text-xl text-white/80 max-w-2xl mx-auto mb-10 leading-relaxed">
              Generate personalized, safe, and optimized travel itineraries in seconds.
              Perfect for solo adventurers who want to explore the world confidently.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                to="/plan"
                className="group flex items-center gap-3 px-8 py-4 bg-white text-primary-600 rounded-2xl font-bold text-lg 
                  hover:bg-primary-50 transition-all duration-300 shadow-xl shadow-black/10
                  hover:shadow-2xl hover:-translate-y-0.5"
              >
                <Globe size={22} />
                Start Planning Free
                <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
              </Link>
              <Link
                to="/hidden-gems"
                className="flex items-center gap-3 px-8 py-4 bg-white/10 backdrop-blur-md text-white rounded-2xl font-semibold text-lg
                  border border-white/20 hover:bg-white/20 transition-all duration-300"
              >
                <Star size={22} />
                Explore Hidden Gems
              </Link>
            </div>

            {/* Stats */}
            <motion.div
              className="flex flex-wrap items-center justify-center gap-8 mt-16"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
            >
              {stats.map((stat, i) => (
                <div key={i} className="text-center">
                  <p className="text-3xl font-bold text-white">{stat.number}</p>
                  <p className="text-sm text-white/60">{stat.label}</p>
                </div>
              ))}
            </motion.div>
          </motion.div>
        </div>

        {/* Wave divider */}
        <div className="absolute bottom-0 left-0 right-0">
          <svg viewBox="0 0 1440 100" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" className="w-full h-16 md:h-24">
            <path d="M0 100L60 87.5C120 75 240 50 360 37.5C480 25 600 25 720 33.3C840 41.7 960 58.3 1080 62.5C1200 66.7 1320 58.3 1380 54.2L1440 50V100H0Z"
              className="fill-surface-50 dark:fill-surface-950" />
          </svg>
        </div>
      </motion.section>

      {/* ===== FEATURES ===== */}
      <section className="py-20 md:py-28 bg-surface-50 dark:bg-surface-950">
        <div className="max-w-7xl mx-auto px-4">
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <span className="text-sm font-semibold text-primary-600 dark:text-primary-400 uppercase tracking-wider">
              Why TriPlanner?
            </span>
            <h2 className="text-3xl md:text-5xl font-bold text-surface-900 dark:text-surface-100 mt-3 mb-4">
              Travel Smarter, Not Harder
            </h2>
            <p className="text-lg text-surface-500 dark:text-surface-400 max-w-2xl mx-auto">
              Our AI understands your mood, budget, safety needs, and energy levels to create the perfect itinerary
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={index}
                  className="glass-card p-6 group"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                >
                  <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-4
                    shadow-lg group-hover:scale-110 transition-transform duration-300`}
                  >
                    <Icon size={22} className="text-white" />
                  </div>
                  <h3 className="text-lg font-semibold text-surface-900 dark:text-surface-100 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-surface-500 dark:text-surface-400 text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ===== POPULAR DESTINATIONS ===== */}
      <section className="py-20 md:py-28 bg-white dark:bg-surface-900">
        <div className="max-w-7xl mx-auto px-4">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <span className="text-sm font-semibold text-primary-600 dark:text-primary-400 uppercase tracking-wider">
              Trending Now
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-surface-900 dark:text-surface-100 mt-3 mb-4">
              Popular Destinations
            </h2>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {destinations.map((dest, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.08 }}
              >
                <Link
                  to={`/plan?destination=${dest.name}`}
                  className="glass-card p-5 text-center group block"
                >
                  <div className="text-5xl mb-3 group-hover:scale-110 transition-transform duration-300">
                    {dest.emoji}
                  </div>
                  <h3 className="font-semibold text-surface-900 dark:text-surface-100 group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">
                    {dest.name}
                  </h3>
                  <span className={`inline-block mt-1 text-xs font-medium px-2 py-0.5 rounded-full bg-gradient-to-r ${dest.color} text-white`}>
                    {dest.tag}
                  </span>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== TESTIMONIALS ===== */}
      <section className="py-20 md:py-28 bg-surface-50 dark:bg-surface-950">
        <div className="max-w-7xl mx-auto px-4">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <span className="text-sm font-semibold text-primary-600 dark:text-primary-400 uppercase tracking-wider">
              Testimonials
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-surface-900 dark:text-surface-100 mt-3">
              Loved by Travelers
            </h2>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div
                key={i}
                className="glass-card p-6"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
              >
                <div className="flex items-center gap-1 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} size={16} className="text-amber-400 fill-amber-400" />
                  ))}
                </div>
                <p className="text-surface-700 dark:text-surface-300 mb-6 leading-relaxed italic">
                  "{t.text}"
                </p>
                <div className="flex items-center gap-3">
                  <span className="text-3xl">{t.avatar}</span>
                  <div>
                    <p className="font-semibold text-surface-900 dark:text-surface-100 text-sm">{t.name}</p>
                    <p className="text-xs text-surface-400">{t.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== CTA SECTION ===== */}
      <section className="relative py-20 md:py-28 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-primary-600 to-accent-600 dark:from-primary-800 dark:to-accent-800" />
        <motion.div
          className="absolute top-1/2 left-1/4 w-96 h-96 rounded-full bg-white/5 blur-3xl"
          animate={{ scale: [1, 1.2, 1] }}
          transition={{ duration: 6, repeat: Infinity }}
        />

        <div className="relative max-w-4xl mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Ready to Plan Your
              <br />Solo Adventure?
            </h2>
            <p className="text-lg text-white/80 mb-10 max-w-xl mx-auto">
              Join thousands of solo travelers who plan smarter with AI.
              Your next unforgettable trip starts here.
            </p>
            <Link
              to="/signup"
              className="group inline-flex items-center gap-3 px-10 py-4 bg-white text-primary-600 rounded-2xl font-bold text-lg
                hover:bg-primary-50 transition-all duration-300 shadow-xl shadow-black/10"
            >
              <MapPin size={22} />
              Get Started Free
              <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ===== FOOTER ===== */}
      <footer className="bg-surface-900 dark:bg-surface-950 text-surface-400 py-16">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-12">
            <div className="col-span-2 md:col-span-1">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center">
                  <Map size={18} className="text-white" />
                </div>
                <span className="text-lg font-bold text-white">TriPlanner</span>
              </div>
              <p className="text-sm leading-relaxed">
                AI-powered travel planning for solo travelers. Plan smart, travel better.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-4 text-sm uppercase tracking-wider">Product</h4>
              <ul className="space-y-2 text-sm">
                <li><Link to="/plan" className="hover:text-primary-400 transition-colors">Trip Planner</Link></li>
                <li><Link to="/safety" className="hover:text-primary-400 transition-colors">Safety System</Link></li>
                <li><Link to="/hidden-gems" className="hover:text-primary-400 transition-colors">Hidden Gems</Link></li>
                <li><Link to="/chatbot" className="hover:text-primary-400 transition-colors">AI Assistant</Link></li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-4 text-sm uppercase tracking-wider">Company</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-primary-400 transition-colors">About Us</a></li>
                <li><a href="#" className="hover:text-primary-400 transition-colors">Careers</a></li>
                <li><a href="#" className="hover:text-primary-400 transition-colors">Blog</a></li>
                <li><a href="#" className="hover:text-primary-400 transition-colors">Contact</a></li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-white mb-4 text-sm uppercase tracking-wider">Legal</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-primary-400 transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-primary-400 transition-colors">Terms of Service</a></li>
                <li><a href="#" className="hover:text-primary-400 transition-colors">Cookie Policy</a></li>
              </ul>
            </div>
          </div>

          <div className="border-t border-surface-800 pt-8 text-center text-sm">
            <p>&copy; {new Date().getFullYear()} TriPlanner. All rights reserved. Made with ❤️ for solo travelers.</p>
          </div>
        </div>
      </footer>
    </AnimatedPage>
  );
}

export default Home;
